include:
  - local: "/includes/skopeo.yml"
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main

variables:
  DSO_REGISTRY: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - image-promotion 

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

skopeo-copy:
  stage: image-promotion
  extends:
    - .skopeo:copy

